In [40]:
import numpy as np

In [41]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

# creating an array

In [42]:
l = [1 , 2 , 3 , 4]
l  #first statment run without print

[1, 2, 3, 4]

In [43]:
arr = np.array(1)
print(arr)

1


In [44]:
a = np.array([[1,2,3] , [4,5,6] , [7,8,9]])  ## convert in numpy array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a2 = np.zeros(5) #float number give 5 time of zero
a2

array([0., 0., 0., 0., 0.])

In [46]:
a3 = np.ones(5) # integer value 5 time of 1
a3

array([1., 1., 1., 1., 1.])

In [47]:
a4 = np.eye(3) # identitity matrix it means cross me 1 vali value aayegi
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
ar1 = np.zeros((3,3)) # it gives 0 value of matrix
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
ar2 = np.ones((3,3)) # it gives 1 value of matrix
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
ar3 = np.arange(10) # range of 0 to 9 given
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
ar4 = np.arange(1,11) # from 1 to 10 given
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
ar5 = np.arange(1 , 11 , 2) # start , end and steps
ar5

array([1, 3, 5, 7, 9])

In [53]:
ar6 = np.linspace(1 , 10 , 5) # random number generated 1 to 10
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [54]:
ar7 = np.full(5,3) # 5 bar 3 aayega
ar7

array([3, 3, 3, 3, 3])

In [55]:
ar8 = np.full((3,3) , 9) # 3 x 3 matrix of 3
ar8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [56]:
r1 = np.random.rand(3,3) #float value of random number 2d
r1

array([[0.53680303, 0.53202437, 0.75067037],
       [0.52078798, 0.29607727, 0.22771348],
       [0.90765589, 0.13838161, 0.6607231 ]])

In [57]:
r2 = np.random.rand(5) # float value of random number 1d 
r2

array([0.03953869, 0.91007862, 0.875648  , 0.528674  , 0.37625489])

In [58]:
r3 = np.random.randint(5) # interger value of random number
r3

1

In [59]:
r4 = np.random.randint(3,10) # start , end
r4

9

In [60]:
r5 = np.random.randint(3 , 10 , 2) # start , end and steps
r5

array([7, 6], dtype=int32)

In [61]:
r6 = np.random.randint(3 , 10  ,(3 , 3)) # 
r6

array([[8, 5, 5],
       [6, 8, 6],
       [6, 9, 5]], dtype=int32)

## Indexing of array

In [62]:
ar = np.random.randint(1 ,10 ,(3,3))
ar

array([[7, 8, 7],
       [2, 5, 3],
       [8, 4, 7]], dtype=int32)

In [63]:
print(ar[-1]) # raw wise indexing
print(ar[0])
print(ar[1])
print(ar[2])
print(ar)

[8 4 7]
[7 8 7]
[2 5 3]
[8 4 7]
[[7 8 7]
 [2 5 3]
 [8 4 7]]


In [64]:
ar2 = np.random.randint(1,11 , (3 , 3))
ar2


array([[ 3, 10,  5],
       [ 8,  9,  8],
       [ 8,  9,  6]], dtype=int32)

In [65]:
print(ar2)# row and colum wise indexing


[[ 3 10  5]
 [ 8  9  8]
 [ 8  9  6]]


In [66]:
#print(ar2) 
print(ar2 [0][0]) # first is aadi row second is ubhi colum

3


In [67]:
print(ar2 [0][1])


10


In [68]:
print(ar2 [0][2])


5


In [69]:
print(ar2 [1][0])


8


In [70]:
print(ar2 [1][1])


9


In [71]:
print(ar2 [1][2])


8


In [72]:
print(ar2 [2][0])


8


In [73]:
print(ar2 [2][1])


9


In [74]:
print(ar2 [2][2])


6


## slicing on array

In [75]:
a = np.arange(1,10) 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a [0:3] # from index 0 to 3

array([1, 2, 3])

In [77]:
a [-1:5:-1] # first -1 is for start and 5 is for end step and last -1 is reverse step

array([9, 8, 7])

In [78]:
a [2:6] # from index 2 to 6

array([3, 4, 5, 6])

In [79]:
a [0:] # from 0 index to end

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a [0::1] # from 0 to end in positive way

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a [0::2] # from 0 to end and 2 is step

array([1, 3, 5, 7, 9])

In [82]:
a [::2] # 0 to end in 2 step

array([1, 3, 5, 7, 9])

In [83]:
a [::-1] # in reverse 0 to end

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## row and colum wise slicing

In [84]:
a2 = np.random.randint(1,10, (3,3))
a2

array([[3, 9, 8],
       [3, 4, 8],
       [7, 1, 4]], dtype=int32)

In [85]:
a2[0:2 , 1] # 0 row 1 colum

array([9, 4], dtype=int32)

In [86]:
a2 [0: , 1]

array([9, 4, 1], dtype=int32)

In [87]:
a2 [ : , : ] #full

array([[3, 9, 8],
       [3, 4, 8],
       [7, 1, 4]], dtype=int32)

In [88]:
a2 [0: , 1: ] #0 row , 1 colum

array([[9, 8],
       [4, 8],
       [1, 4]], dtype=int32)

## shape ,size and Datatype of array

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
print(a.shape) # shape 

(9,)


In [91]:
print(a.size) # number of element

9


In [92]:
a2

array([[3, 9, 8],
       [3, 4, 8],
       [7, 1, 4]], dtype=int32)

In [93]:
print(a2.shape) 

(3, 3)


In [94]:
print(a.dtype) # for vactor

int64


In [95]:
print(a2.dtype) # for matrix

int32


In [96]:
a1 = np.array([16 , 81 , 64 , 121 , 9]) # root kadhe che
np.sqrt(a1)

array([ 4.,  9.,  8., 11.,  3.])

In [97]:
a1 = 10 , 20 , 30
a2 = 40 , 50 , 60 

In [98]:
a1 + a2  

(10, 20, 30, 40, 50, 60)