In [83]:
import numpy as np

Mathematical operations

In [84]:
# we can perform mathematical operations on only matrix not list

In [85]:
a1 = np.array((1 , 2 , 3 , 4 , 5))
a1

array([1, 2, 3, 4, 5])

In [86]:
a2 = np.array((6 , 7 , 8 , 9 , 10))
a2

array([ 6,  7,  8,  9, 10])

In [87]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [88]:
a1 - a2


array([-5, -5, -5, -5, -5])

In [89]:
a1 * a2


array([ 6, 14, 24, 36, 50])

In [90]:
a1 / a2


array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [91]:
# 1st  list 2nd list ke sath jud jati hai

In [92]:
a = 10 , 20 , 30 , 40
b = 50 , 60 , 70 , 80
a + b 

(10, 20, 30, 40, 50, 60, 70, 80)

In [93]:
ans = a1**2 # squar kar deta hai
ans

array([ 1,  4,  9, 16, 25])

In [94]:
squar = np.sqrt(ans) # root nikalta hai
print(squar)
#squar

[1. 2. 3. 4. 5.]


In [95]:
a3 = np.array([1.2 , 3.5 , 6.9 , 4.1 , 9])
a3

array([1.2, 3.5, 6.9, 4.1, 9. ])

In [96]:
np.floor(a3) # convert in to lowest interger 

array([1., 3., 6., 4., 9.])

In [97]:
np.ceil(a3) # convert into highest interger

array([2., 4., 7., 5., 9.])

In [98]:
np.round(a3) # round figur nikal ke deta hai

array([1., 4., 7., 4., 9.])

## Combaing array

In [99]:
a1

array([1, 2, 3, 4, 5])

In [100]:
a2

array([ 6,  7,  8,  9, 10])

In [101]:
np.concatenate((a1 , a2)) # merge vector / 1d array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
arr1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
arr2 = np.array([[11 , 12 , 13] , [14 , 15 , 16] , [17 , 18 , 19]])


In [103]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [105]:
np.vstack((arr1,arr2)) # add two 2d array in vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [106]:
np.hstack((arr1,arr2)) # add two 2d array in horizontally

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [107]:
arr1.flatten() # convert 2d array in 1d array/vactor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Splitting array

In [108]:
arr = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.split(arr , 3)# convert 1d array in 2d matrix

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [110]:
arr3 = np.array([[1 , 2 , 3 , 4 , 5 , 6],
                [11 , 12 , 13 , 14 , 15 , 16]])
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [111]:
np.hsplit(arr3 , 3) #2d convert in 3d horizontally

[array([[ 1,  2],
        [11, 12]]),
 array([[ 3,  4],
        [13, 14]]),
 array([[ 5,  6],
        [15, 16]])]

In [112]:
np.vsplit(arr3 , 2) # vertically converted

[array([[1, 2, 3, 4, 5, 6]]), array([[11, 12, 13, 14, 15, 16]])]

## searching

In [113]:
a1 = np.array([12 , 35 , 58 , 90])
a1

array([12, 35, 58, 90])

In [114]:
print(np.where(a1 == 12)) # give index of value from array 
print(np.where(a1 == 35))
print(np.where(a1 == 58))
print(np.where(a1 == 90))


(array([0]),)
(array([1]),)
(array([2]),)
(array([3]),)


In [115]:
a2 = np.array([1 , 5 , 6 , 9 , 7 , 3 , 5 , 5])
a2

array([1, 5, 6, 9, 7, 3, 5, 5])

In [116]:
np.where(a2 == 5) # give indexes of value(5) from array 

(array([1, 6, 7]),)

In [117]:
np.where(a2 > 5) # give index of big number than 5

(array([2, 3, 4]),)

In [118]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
np.where(arr1 == 5) # first ans is aadi row and second ans is ubhi colum

(array([1]), array([1]))

In [120]:
arr4 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
np.where(arr4 == 2) # index of 2

(array([0]), array([1]))

## sorting of array

In [122]:
a1

array([12, 35, 58, 90])

In [ ]:
a2 =  np.sort(a1) # sorting in asecending order
a2


array([12, 35, 58, 90])

In [124]:
a3 = np.sort(a2)[ : :-1] # sorting in decending order
print(a3)


[90 58 35 12]


In [125]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sort(arr4) # sorting in asecending order

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sort(arr4, axis=1) #asecending order raw wise

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sort(arr4, axis=1)[:, ::-1] #decending order column wise

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

## Aggregating & ststical function

In [130]:
a1

array([12, 35, 58, 90])

In [ ]:
np.sum(a1) # aditation

np.int64(195)

In [ ]:
np.mean(a1) # given average

np.float64(48.75)

In [ ]:
np.median(a1) # 12 , 35 , 58 , 90 --> 35 + 58 / 2 --> madhayak

np.float64(46.5)

In [ ]:
np.max(a1) # maximum value

np.int64(90)

In [ ]:
np.min(a1) # minimum value


np.int64(12)

In [ ]:
np.std(a1) # har 1 point ki min ki duri

np.float64(28.838992700855556)

In [ ]:
np.var(a1) # squar of std

np.float64(831.6875)

In [139]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.sum(arr4)

np.int64(45)

In [ ]:
np.sum(arr4 , axis = 1) # row wise sum

array([ 6, 15, 24])

In [142]:
np.sum(arr4 , axis = 0) # column wise sum

array([12, 15, 18])