In [1]:
import numpy as np

## Boolean indexing (Filering Array) 

In [2]:
arr = np.array([10 , 20 , 30 , 40 , 50 ])
arr

array([10, 20, 30, 40, 50])

In [3]:
l = [True , False , False , True , True]
l

[True, False, False, True, True]

In [4]:
arr

array([10, 20, 30, 40, 50])

In [5]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

10
20
30
40
50


In [6]:
arr[True , False , False , True , True]
arr[l] # where ans is true value were given 

array([10, 40, 50])

In [7]:
arr


array([10, 20, 30, 40, 50])

In [8]:
arr2 = np.array([12 , 85 , 60 , 90 ,75])
arr2

array([12, 85, 60, 90, 75])

In [9]:
l2 =(arr2%2==0)
l2 # when condition is right ans is true and condition is wrong ans is false 

array([ True, False,  True,  True, False])

In [10]:
arr2[l2] # ans is in number

array([12, 60, 90])

In [11]:
arr2 [arr2 % 2 == 0] # ans is in numbers when condition is true

array([12, 60, 90])

In [12]:
age = np.array([42 , 54 , 59 , 76 , 100])
age

array([ 42,  54,  59,  76, 100])

In [13]:
age [age > 50]

array([ 54,  59,  76, 100])

In [14]:
age [age == 100]

array([100])

In [15]:
a2 = np.array([[3 , 2 ,5] , [7 , 8 , 9] , [11 , 12 , 19] ])
a2

array([[ 3,  2,  5],
       [ 7,  8,  9],
       [11, 12, 19]])

In [16]:
l1 = [True , False ,True] # row wise boolean index
l1

[True, False, True]

In [17]:
a2[l1]# row wise boolean index

array([[ 3,  2,  5],
       [11, 12, 19]])

## Boolean mask

In [18]:
arr

array([10, 20, 30, 40, 50])

In [19]:
l

[True, False, False, True, True]

In [20]:
print(np.ma.array(arr , mask = 1))# missing dataes are given


[-- -- -- -- --]


In [21]:
arr

array([10, 20, 30, 40, 50])

In [22]:
odd_number = (np.ma.array(arr, mask = arr%2==0))
print(odd_number)

[-- -- -- -- --]


## Reshaping Array

In [23]:
a2

array([[ 3,  2,  5],
       [ 7,  8,  9],
       [11, 12, 19]])

In [24]:
a2.flatten() # convert 2d array in 1d

array([ 3,  2,  5,  7,  8,  9, 11, 12, 19])

In [ ]:
a2.reshape(-1) # convert into 1d array but -1 means automatic decide its shape

array([ 3,  2,  5,  7,  8,  9, 11, 12, 19])

In [26]:
a2.ravel()# convert (multidimention)2d array in 1d

array([ 3,  2,  5,  7,  8,  9, 11, 12, 19])

In [27]:
a1d = np.arange(12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a1d.reshape(4,3) # 1d in convert in 2d --> 4 rows and 3 column

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
a1d.reshape(-1,3) # -1 means automatic shape decide of row and 3 column

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
a1d.reshape(3,-1) # -1 means automatic shape decide of raws and 3 column 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a1d.reshape(2,3,2) # 2 means 2d array and 3 means raws and 2nd 2 means column

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## Broadcasting of Array

Broadcasting is a powerful meachnism is NumPy that allows array operations between arrays of different shapes without copying data.

In simple terms : Brodcasting allows you to automatically expand smaller arrays to match the shape of larger arrays during operatins like addition , multiplication , etc...

### Types of brodcasting

- scalar brodcasting
- Vactor brodcasting
- Matrix brodcasting

# scalar brodcasting

In [32]:
# one element array

In [33]:
arr

array([10, 20, 30, 40, 50])

In [34]:
s1  = [3]
s2 = 5 # this value add in every vactor
s3 = np.array([6])


In [35]:
print(arr + s1)

[13 23 33 43 53]


In [50]:
arr + s2

array([15, 25, 35, 45, 55])

In [37]:
arr + s3

array([16, 26, 36, 46, 56])

# vactor brodcasting

- 1. row vactor
- 2. column vactor

# row vactor

In [38]:
a1 = np.array([[1 , 2 , 3] , [4 , 5 , 6]])  # shape (2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2 = np.array([[10 , 20 , 30]]) # shape (3,)
a2

array([[10, 20, 30]])

In [40]:
print(a1 + a2)
# a1.shape = (2,3)
# a2.shape = (3, )

[[11 22 33]
 [14 25 36]]


# column vactor

In [41]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a2 = np.array([[10] , [20]])
a2

array([[10],
       [20]])

In [43]:
a2 = np.array([10,20]).reshape(-1 , 1)
a2


array([[10],
       [20]])

In [44]:
print(a1 + a2)

[[11 12 13]
 [24 25 26]]


In [45]:
a2.shape = (2 , 1)
a2

array([[10],
       [20]])

## Matrix Brodcasting

#### Brodcasting happens between matrix of different shapes if they satisfy brodcasting rules.

In [46]:
a1 = np.array([[1],[2]]) # 1,1,1
                         # 2,2,2
                         
a2 = np.array([[10 , 20 ,30]]) #10 20 30
                               #10 20 30

In [47]:
print(a1)
print()
print(a2)
print()


[[1]
 [2]]

[[10 20 30]]



In [48]:
a3 = a1 + a2
print(a3)

[[11 21 31]
 [12 22 32]]


In [49]:
# a1 --> (2 , 1) -->expened across columns
# a2 --> (1 , 3) -->expened across raws
# result shape  --> (2 , 3)